# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.ImageField(upload_to='api/storeimages/'),
        ),
    ]
