# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170828_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('name', models.TextField()),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
    ]
